version: '3.6'

services:
  app:
    build: .
    environment:
      MONGO_USER: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB: "${MONGO_INITDB_DATABASE}"
    ports:
      - 8000:8000
    volumes:
      - .:/code

  db:
    image: mongo:latest
    env_file: .env
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/data/db/:/data/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    ports:
      - "27017:27017"

